accounts/urls.py
from django.conf.urls import url

from .views import logout_view
from .views import RegisterView
from .views import LoginView
from .views import AccountView
from .views import InboxView
from .views import InboxDetailView
from .views import SelfAccountView
from .views import PrivateMessageView

urlpatterns = [
    url(r"^$", SelfAccountView.as_view(), name='self_account'),
    url(r"^logout/$", logout_view, name='logout'),
    url(r"^login/$", LoginView.as_view(), name='login'),
    url(r"^register/$", RegisterView.as_view(), name='register'),
    url(r"^inbox/$", InboxView.as_view(template_name='landing/inbox.html'), name='inbox'),
    url(r"^inbox/(?P<pk>\d+)$", InboxDetailView.as_view(), name='inbox_detail'),
    url(r"^(?P<username>\w+)/send_message/$", PrivateMessageView.as_view(), name='send_mail'),
    url(r"^(?P<username>\w+)/$", AccountView.as_view(), name='account'),
]

forum/urls.py
from django.conf.urls import url, include
from django.contrib import admin

import topics.urls
import accounts.urls

from section.views import SectionView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include(accounts.urls)),
    url(r'^$', SectionView.as_view(), name='index'),
    url(r'^(?P<slug>[\w-]+)/', include(topics.urls)),
    url(r'^markdown/', include('django_bootstrap_markdown.urls')),

]

topics/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from .views import MessageListView, TopAddView, TopicView, MessageAddView

urlpatterns = [
    url(r"^$", TopicView.as_view(), name='topic'),
    url(r"^add/$", login_required(TopAddView.as_view()), name='add_topic'),
    url(r"^(?P<pk>[0-9]+)/(page(?P<page>\d+))?$", MessageListView.as_view(), name='topic_messages'),
    url(r"^create/(?P<pk>[0-9]+)$",
        login_required(MessageAddView.as_view()),
        name='add_topic_message',),
]

accounts/models.py
from django.utils import timezone
from django.contrib.auth.models import User
from django.db import models
from forum.settings import MEDIA_ROOT


class UserDetails(models.Model):
    user = models.OneToOneField(User)
    avatar = models.ImageField(
        upload_to='%s/user_pics' % (MEDIA_ROOT, ),
        height_field=100,
        width_field=100,
        blank=True
    )

    @property
    def get_post_frequency(self):
        posts = self.user.message_set.count()
        date_joined = self.user.date_joined
        delta = (timezone.now() - date_joined).days

        if not posts:
            return 'Нет сообщений'

        elif not delta:
            return '%s сообщений за день' % (posts,)

        else:
            frequency = round(posts/delta, 1)
            return '%s сообщений в день' % (frequency,)

    def __str__(self):
        return 'user: %s additional info' % (self.user.username,)


class UserMessages(models.Model):
    receiver = models.ForeignKey(User)
    sender = models.ForeignKey(User, related_name='sender')
    title = models.CharField(max_length=150)
    message = models.TextField()
    read = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-date']

topics/models.py
from django.db import models
from django.contrib.auth.models import User

from section.models import Section


TOPIC_STATE = (
    ('C', 'Closed'),
    ('O', 'Open'),
    ('S', 'Closed by section')
)


class Moder(models.Model):
    moder = models.ForeignKey(User)

    class Meta:
        verbose_name_plural = 'Модераторы'

    def __str__(self):
        return self.moder.username


class Topic(models.Model):
    name = models.CharField(verbose_name='Тема', max_length=1000, unique_for_date='date')
    short_description = models.CharField(verbose_name='Карткое описание',
                                         max_length=150,
                                         blank=True,
                                         null=True)
    date = models.DateField(auto_now_add=True)
    state = models.CharField(max_length=1, choices=TOPIC_STATE, default='O')
    author = models.ForeignKey(User)
    moder = models.ForeignKey(Moder)
    section = models.ForeignKey(Section)

    class Meta:
        verbose_name_plural = 'Темы'

    def topic_icon(self):
        if self.state == 'O':
            return 'fa fa-comment-o fa-3x'
        else:
            return 'fa fa-lock fa-3x'

    def get_absolute_url(self):
        return "/%s/%s" % (self.section.slug ,self.pk)

    def __str__(self):
        return self.name


class Message(models.Model):
    title = models.CharField(max_length=150, blank=True)
    author = models.ForeignKey(User, verbose_name='Автор')
    topic = models.ForeignKey(Topic, verbose_name='Тема')
    date = models.DateField('Дата', auto_now_add=True)
    text = models.TextField('Текст сообщения')
    rate = models.IntegerField('Рейтинг', default=0)

    class Meta:
        verbose_name_plural = 'Сообщения'
        verbose_name = "Сообщение"

    def colorize(self):
        code = '*code*'
        return self.text.split(code) if self.text.count(code) == 2 else False

    def __str__(self):
        return self.text

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=True)
    confirm_terms = forms.BooleanField(
        widget=forms.CheckboxInput(),
        label='Я согласен с правилами',
        error_messages={'required': 'Вы не согласились с правилами'}
    )

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

topics/forms.py
from django import forms
from topics.models import Message


class MessageModelForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('text', )
        labels = {
            'text': 'Текст сообщения:'
        }

accounts/views.py
from django.contrib.auth import logout
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib import messages

from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseForbidden
from django.shortcuts import redirect

from django.views.generic import FormView
from django.views.generic import DetailView
from django.views.generic import TemplateView
from django.views.generic import CreateView

from .forms import UserCreateForm
from .models import UserDetails, UserMessages


def logout_view(request):
    logout(request)
    messages.info(request, 'Вы успешно вышли!' )
    return redirect(
        reverse_lazy('login')
    )


class LoginView(FormView):
    form_class = AuthenticationForm
    template_name = 'landing/login.html'
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)
        login(self.request, user)
        messages.info(self.request, 'Вы успешно вошли под аккаунтом  %s!' % (username,))

        # hint to get back on requested page.
        self.success_url = self.request.GET.get('next', False) or self.success_url
        
        return super(LoginView, self).form_valid(form)


class RegisterView(FormView):
    form_class = UserCreateForm
    template_name = 'landing/register.html'
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        username = form.cleaned_data['username']
        email = form.cleaned_data['email']
        password = form.cleaned_data['password1']
        User.objects.create_user(username=username, email=email, password=password)
        user = authenticate(username=username, password=password)

        UserDetails.objects.create(user=user)

        login(self.request, user)

        messages.info(self.request, 'Аккаунт %s успешно создан!' % (username,))
        return super(RegisterView, self).form_valid(form)


class AccountView(DetailView):
    model = User
    template_name = 'landing/account.html'
    slug_url_kwarg = 'username'
    slug_field = 'username'
    context_object_name = 'user_profile'


class SelfAccountView(LoginRequiredMixin, TemplateView):
    template_name = 'landing/account_self.html'


class InboxView(LoginRequiredMixin, TemplateView):
    template_name = 'landing/inbox.html'

    def get_context_data(self, **kwargs):
        context = super(InboxView, self).get_context_data()
        user = self.request.user
        context['user_messages'] = UserMessages.objects.filter(receiver=user)
        return context


class InboxDetailView(LoginRequiredMixin,DetailView):
    model = UserMessages
    template_name = 'landing/inbox_detail.html'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()

        if self.object.receiver != self.request.user:
            return HttpResponseForbidden()

        self.object.read = True
        self.object.save()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


class PrivateMessageView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('login')
    template_name = 'landing/add_new_private_message.html'
    model = UserMessages
    fields = ('title', 'message')

    def form_valid(self, form):
        message = form.save(commit=False)
        message.sender = self.request.user
        username = self.kwargs['username']

        try:
            receiver = User.objects.get(username=username)
            message.receiver = receiver
            message.save()

            messages.info(self.request, 'Сообщение пользователю %s успешно отправленно' % (receiver,))

        except User.DoesNotExist:
            messages.error(self.request, 'Пользователь %s не найден' % username)
            return redirect(
                reverse_lazy('self_account')
            )
        return redirect(
            reverse_lazy('pm_history', kwargs={'username': username})
        )

topics/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import CreateView, ListView
from django_bootstrap_markdown.widgets import MarkdownInput

from section.models import Section
from .models import Topic, Moder, Message


class TopicView(ListView):
    model = Topic
    template_name = 'landing/topic.html'
    context_object_name = 'topics'
    paginate_by = 5

    def get_queryset(self):
        qs = super(TopicView, self).get_queryset()
        slug = self.kwargs['slug']
        qs = qs.filter(section__slug=slug)

        search_query = self.request.GET.get('q')
        if search_query is not None:
            qs = qs.filter(name__icontains=search_query)

        return qs

    def get_context_data(self, **kwargs):
        context = super(TopicView, self).get_context_data()
        slug = self.kwargs['slug']
        context['slug'] = slug
        context['section'] = get_object_or_404(Section, slug=slug)
        return context


class TopAddView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('login')
    template_name = 'landing/add_new_topic.html'
    model = Topic
    fields = ('name', 'short_description')

    def form_valid(self, form):
        topic = form.save(commit=False)
        topic.author = self.request.user
        topic.moder = Moder.objects.get(pk=1)
        slug = self.kwargs['slug']
        topic.section = get_object_or_404(Section, slug=slug)
        messages.info(self.request, 'Тема успешно добавлена!')

        topic.save()

        return redirect(
            reverse_lazy('topic', kwargs={'slug': slug})
        )


class MessageAddView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('login')
    template_name = 'landing/add_new_message.html'
    model = Message
    fields = ('title', 'text',)

    def get_form(self, form_class=None):
        form = super(MessageAddView, self).get_form()
        form.fields['text'].widget = MarkdownInput()
        return form

    def form_valid(self, form):
        message = form.save(commit=False)
        message.author = self.request.user
        pk = self.kwargs['pk']
        slug = self.kwargs['slug']
        topic = get_object_or_404(Topic, pk=pk)
        message.topic = topic

        if not message.title:
            if topic.message_set.count() == 0:
                prefix = ''
            else:
                prefix = 'RE:'
            message.title = '%s %s' % (prefix,topic.name,)

        message.save()
        messages.info(self.request, 'Сообщение успешно добавлено')

        return redirect(
            reverse_lazy('topic_messages', kwargs={'slug': slug, 'pk': pk})
        )


class MessageListView(ListView):
    template_name = 'landing/messages.html'
    model = Message
    context_object_name = 'topic_messages'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(MessageListView, self).get_context_data()
        pk = self.kwargs['pk']
        topic = get_object_or_404(Topic, pk=pk)
        context['topic'] = topic

        return context

    def get_queryset(self):
        qs = super(MessageListView, self).get_queryset()
        pk = self.kwargs['pk']
        topic = get_object_or_404(Topic, pk=pk)
        qs = qs.filter(topic=topic)

        search_query = self.request.GET.get('q')
        if search_query is not None:
            qs = qs.filter(text__icontains=search_query)

        return qs

templates/landing/account.html
{% extends 'landing/account_self.html' %}


{% block subheader_btn %}
    <a class="btn btn-primary pull-right" href="{% url 'send_mail' username=user_profile.username %}" style="margin-top: 23px">
        <i class="fa fa-pencil-square"> Написать личное сообщение </i>
    </a>
{% endblock %}

templates/landing/account_self.html
{% extends 'landing/deep_base.html' %}

{% block infopanel %}
{% endblock %}

{% block subheader %}
 {{ user.username }}
{% endblock %}

{% block subheader_btn %}
    <a class="btn btn-primary pull-right" href="{% url 'inbox' %}" style="margin-top: 23px">
        <i class="fa fa-comments-o"> Личные сообщения </i>
        {% if new_incoming.count %}
           <span class="badge"> {{ new_incoming.count }} </span>
        {% endif %}
    </a>
{% endblock %}


{% block page_content %}
<div class="container">
        Статистика: <br>
        {{ user.userdetails.get_post_frequency }}
        {% if user.message_set.count %}
            Последние сообщения:
            {% for i in user.message_set.all %}
                <p>{{ i.text | truncatechars:"20"}}</p>
            {% endfor %}
        {% endif %}
</div>
{% endblock %}

templates/landing/add_new_message.html
{% extends 'landing/deep_base.html' %}

{% block html_head %}
        {{ form.media }}
{% endblock %}

{% load bootstrap %}

{% block subheader %}
Добавить новое сообщение
{% endblock %}

{% block infopanel %}
{% endblock %}


{% block page_content %}
    <div class="container">
        <div class="form-group">
            <form method="post">
                {% csrf_token %}
                {{ form|bootstrap }}
                <input type="submit" class="btn btn-primary btn-block" value="Написать"/>
            </form>
        </div>
    </div>

{% endblock %}

templates/landing/add_new_private_message.html
{% extends 'landing/deep_base.html' %}
{% load bootstrap %}

{% block subheader %}
Личное сообщение
{% endblock %}

{% block infopanel %}
{% endblock %}


{% block page_content %}
    <div class="container">

        {% for message in history %}
        {% if user == message.sender %}
            <span class="text-left">{{ message.message|linebreaks }}</span>
        {% else %}
            <span class="text-right">{{ message.message|linebreaks }}</span>
        {% endif %}
    {% endfor %}
        <div class="form-group">
            <form method="post">
                {% csrf_token %}
                {{ form|bootstrap }}
                <input type="submit" class="btn btn-primary btn-block" value="Написать"/>
            </form>
        </div>
    </div>

{% endblock %}

templates/landing/add_new_topic.html
{% extends 'landing/deep_base.html' %}
{% load bootstrap %}

{% block subheader %}
Добавить новую тему
{% endblock %}

{% block infopanel %}
{% endblock %}


{% block page_content %}

    <div class="container">
        <h2><i class="fa fa-exclamation-triangle"></i> Правила добавления новой темы:</h2>

    {% lorem 1 p %}
        <form method="post">
        {% csrf_token %}
        {{ form|bootstrap}}

        <div class="form-group">
            <button class="btn btn-primary btn-lg btn-block" type="submit" style="margin-top: 10px">Создать тему</button>
        </div>
    </form>
    </div>

{% endblock %}

templates/landing/back_to_top_btn.html
<a id="back-to-top" href="#" style="display: none">
    <i class="fa fa-angle-up"></i>
</a>

templates/landing/base.html
{% load  staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
        <script src="{% static 'js/jquery.js' %}"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="{% static 'css/bootstrap-theme.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <script src="{% static 'js/landing.js' %}"></script>

    {% block html_head %}
    {% endblock %}

</head>
<body>

<div id="header" class="navbar-fixed-top">
    <div class="container">

        <ol class="list-inline pull-left">
          <li>
              <a href="{% url 'index' %}"><i class="fa fa-home"> Домой</i></a>
              {% block breadcrumb %}
              {% endblock %}
          </li>
        </ol>

        <ol id="myNavbar" class="list-inline pull-right">
            <li class="list-inline-item hidden-xs"><a href="/obshchaia-informatsiia-o-forumecc68c/1/">FAQ</a></li>
            <li class="list-inline-item  hidden-xs"><a href="#"><i class="fa fa-search"></i></a></li>

            {% if user.is_authenticated %}
                <li class="list-inline-item "><a href="{% url 'self_account' %}">{{ user.username }}</a>

                {% if new_incoming.count  %}
                   <i id="blink" class="fa fa-envelope" style="color: black;"></i>
                {% endif %}

                </li>
                <li class="list-inline-item"><a href="{% url 'logout' %}"><i class="fa fa-sign-out"> Выйти</i></a></li>
                <li class="list-inline-item"><a href="#"><i class="fa fa-bars"></i></a></li>
            {% else %}
                 <li class="list-inline-item"><a id="popup" href="{% url 'login' %}"><i class="fa fa-sign-in"> Войти</i></a></li>
                 <li class="list-inline-item"><a href="{% url 'register' %}">Зарегестрироваться</a></li>
            {% endif %}

        </ol>
    </div>
</div>


{% if messages %}
<div class="message-alert col-md-8 col-md-offset-2 text-center">
    {% for message in messages %}
            <a href="#" class="close {{ message.tags }}" data-dismiss="alert" aria-label="close">&times;</a>
            {{ message }}
    {% endfor %}
</div>
{% else %}
    <span class="close none" style="display: none"></span>
{% endif %}

{% block content %}
    <div id="site-desc-full">
        <div id="page-description" class="text-md-center">
                <h1>Itea Forum Project</h1>
                <h6>communicate with no limits</h6>
        </div>
    </div>
    <div class="row" >

        <div class="container" >
            {% for section in sections %}
            <table class="table table-hover">
                <thead>
                <tr>
                             <th colspan="6"  class="text-center"  style="border-bottom: none"><a href="{{ section.slug }}">{{ section.name }}</a></th>

                </tr>
                <tr>
                    <th>Состояние</th>
{#                    <th><a href="{{ section.slug }}">{{ section.name }}</a></th>#}
                    <th>Тема</th>
                    <th>rss</th>
                    <th class="hidden-md-down text-center">Всего сообщений</th>
                    <th class="text-center">Автор</th>
                    <th class="text-center hidden-xs hidden-sm">Последнее сообщение <i class="fa fa-minus-circle toggle-topic pull-right"></i></th>
                </tr>
                </thead>

                <tbody>
                {% for topic in section.last_five %}
                    <tr>
                        <td class="col-md-1 text-center">
                            <i class="{{ topic.topic_icon }}"></i>
                        </td>

                        <td class="col-md-6">
                            <h4>
                                {% if topic.message_set.count >= 10 %}
                                    <i data-toggle="tooltip" data-placement="bottom" title="Hot" class="fa fa-fire" style="color: red; cursor: help"></i>
                                {% endif %}

                                <a href="{{ topic.get_absolute_url }}">{{ topic.name }} </a>
                            </h4>
                            <small>{{ topic.short_description }}</small>
                        </td>

                        <td><i class="fa fa-rss"></i></td>

                        <td class="text-center">{{ topic.message_set.count }}</td>

                        <td class="text-center">
                            Автор: <a href="{% url 'account' username=topic.author %}">{{ topic.author }}</a>
                            <br>
                            <small><i class="fa fa-clock-o"></i> {{ topic.date }}</small>
                        </td>

                        {% if topic.message_set.count  %}
                            <td class="hidden-xs hidden-sm text-center">
                                Автор: <a href="{% url 'account' username=topic.message_set.last.author %}">{{ topic.message_set.last.author }}</a>
                                <br>
                                <small><i class="fa fa-clock-o"></i> {{ topic.message_set.last.date }}</small>
                            </td>
                        {% else %}
                            <td class="hidden-xs hidden-sm text-center">Нет сообщений</td>
                        {% endif %}

                    </tr>

                {% endfor %}
                </tbody>
            </table>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

    <form id="popup-login" class="form-signin" method="post" action="{% url 'login' %}">
        <h2 class="form-signin-heading">Пожалуйста, введите логин и пароль</h2>
        {% csrf_token %}

        <div class="form-group">
            <label class="control-label  " for="id_username">Имя пользователя</label>
            <div class=" ">
                <input class=" form-control" id="id_username" maxlength="254" name="username" type="text">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label  " for="id_password">Пароль</label>
            <div class=" ">
                <input class=" form-control" id="id_password" name="password" type="password">
            </div>
        </div>

        <div class="form-group">
            <button style="margin-top: 15px" class="btn btn-lg btn-primary btn-block" type="submit">Войти</button>
        </div>
    </form>

{% include 'landing/back_to_top_btn.html' %}
{#{% include 'landing/footer.html' %}#}

</body>
</html>

templates/landing/footer.html
    <div id="footer">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="col-md-4">
                    Who is online <br>
                    In total there are 6 users online :: 1 registered, 0 hidden and 5 guests <br>
                    based on users active over the past 5 minutes <br>
                    Most users ever online was 26 on 25 Dec 2015, 08:29 <br>
                    Registered users: Bing [Bot]<br>
                    Legend: Administrators, Global moderators, Bots, Registered users
                </div>

                <div class="col-md-4">
                    Important links
                    <ul>
                        <li>Frequently Asked Questions</li>
                        <li>BBCode Examples</li>
                        <li>Empty Link</li>
                        <li>Creating an account</li>
                    </ul>
                </div>

                <div class="col-md-4">
                    About us <br>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                    Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                </div>

                <hr>

            </div>
        </div>
        <div class="row">
            <div class="col-md-10 col-md-offset-1 text-center">
                <hr style="border-color: #DBDBDB;">

                <div class="col-md-3">Total posts <br> 90</div>
                <div class="col-md-3">Total topics <br> 22</div>
                <div class="col-md-3">Total members <br> 64</div>
                <div class="col-md-3">Our newest member <br> <strong>cyusuf</strong></div>

            </div>
        </div>
    </div>
    <div id="sub-footer">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="col-md-3">
                Powered by Python Django Forum Software &copy;
            </div>
        </div>
    </div>
</div>

templates/landing/inbox.html
{% extends 'landing/account_self.html' %}


{% block subheader_btn %}
{% endblock %}

{% block subheader %}
    Входящие сообщения
{% endblock %}

{% block breadcrumb %}
/ <a href="{% url 'self_account' %}"> {{ user.username }}</a>
{% endblock %}

{% block page_content %}
    {% for incoming in user_messages %}
        {% if incoming.read %}
            <a href="{% url 'inbox_detail' pk=incoming.id  %}">{{ incoming.title }}</a> <br>
            from: {{ incoming.sender.username }}<br>
            message: {{ incoming.message | linebreaks }} <br>
            date: {{ incoming.date }} <br>
        {% else %}
            <b>
               <a href="{% url 'inbox_detail' pk=incoming.id  %}">{{ incoming.title }}</a> <br>
               from:  {{ incoming.sender.username }}<br>
               message:  {{ incoming.message |linebreaks }} <br>
               date: {{ incoming.date }} <br>
            </b>
        {% endif %}
    {% endfor %}
{% endblock %}

templates/landing/inbox_detail.html
{% extends 'landing/account_self.html' %}

{% block subheader %}
    Входящее сообщение от {{ object.sender.username }}
{% endblock %}

{% block breadcrumb %}
/ <a href="{% url 'self_account' %}"> {{ user.username }}</a>
/ <a href="{% url 'inbox' %}"> Личные сообщения </a>
{% endblock %}

{% block subheader_btn %}
    <a class="btn btn-primary pull-right" href="{% url 'send_mail' username=object.sender.username %}" style="margin-top: 23px">
        <i class="fa fa-pencil-square"> Ответить </i>
    </a>
{% endblock %}

{% block page_content %}
{{ object.sender.username }}<br>
{{ object.title }} <br>
{{ object.message | linebreaks }} <br>
{{ object.date }}
{% endblock %}

templates/landing/register.html
{% extends 'landing/login.html' %}
{% load bootstrap %}

{% block form %}

    <form class="form-horizontal" method="post">
        <h2 class="form-signup-heading">Пожалуйста, введите Информацию</h2>
        {% csrf_token %}
        {{ form|bootstrap}}

        <div class="form-group">
            <button class="btn btn-lg btn-primary btn-block" type="submit" style="margin-top: 10px">Зарегестрироваться</button>
        </div>
    </form>

    <style>

.form-group {
    margin-bottom: -4px;
}
    </style>

{% endblock %}

templates/landing/topic.html
{% extends 'landing/deep_base.html' %}

{% block subheader %}
    {{ section }}
{% endblock %}

{% block subheader_btn %}
    {% if section.is_open %}
        <a class="btn btn-primary pull-right" href="{% url 'add_topic' slug=slug %}" style="margin-top: 23px">
            <i class="fa fa-pencil"> Создать новую тему</i>
        </a>
    {% else %}
        <a class="btn btn-primary pull-right disabled" href="#" style="margin-top: 23px">
            <i class="fa fa-lock"> Раздел закрыт</i>
        </a>
    {% endif %}

{% endblock %}


{% block infopanel_text %}
    Тем: {{ section.topic_set.count }}
{% endblock %}


{% block page_content %}

    <div class="row" >
        <div class="container" >
            <table class="table table-hover">
                <thead>
                <tr>
                    <th></th>
                    <th>Тема</th>
                    <th>rss</th>
                    <th class="hidden-md-down text-center">Всего сообщений</th>
                    <th class="text-center">Автор</th>
                    <th class="text-right hidden-xs hidden-sm">Последнее сообщение</th>
                </tr>
                </thead>
                <tbody>
                {% for topic in topics %}

                    <tr>
                        <td class="col-md-1 text-center">
                            <i class="{{ topic.topic_icon }}"></i>
                        </td>

                        <td>
                            <h4>
                                {% if topic.message_set.count >= 10 %}
                                    <i data-toggle="tooltip" data-placement="bottom" title="Hot" class="fa fa-fire" style="color: red; cursor: help"></i>
                                {% endif %}

                                <a href="{{ topic.get_absolute_url }}">{{ topic.name }}</a>
                            </h4>
                        </td>

                        <td><i class="fa fa-rss"></i></td>

                        <td class="text-center">{{ topic.message_set.count }}</td>

                        <td class="text-center">
                            Автор: <a href="{% url 'account' username=topic.author %}">{{ topic.author }}</a>
                            <br>
                            <small><i class="fa fa-clock-o"></i> {{ topic.date }}</small>
                        </td>

                        {% if topic.message_set.count  %}
                            <td class="hidden-xs hidden-sm text-right">
                                Автор: <a href="{% url 'account' username=topic.message_set.last.author %}">{{ topic.message_set.last.author }}</a>
                                <br>
                                <small><i class="fa fa-clock-o"></i> {{ topic.message_set.last.date }}</small>
                            </td>
                        {% else %}
                            <td class="hidden-xs hidden-sm text-right">Нет сообщений</td>
                        {% endif %}

                    </tr>

                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock page_content %}